// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.2
// source: test-proto.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestServiceClient interface {
	TestServer(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
	TestStreamClientServer(ctx context.Context, opts ...grpc.CallOption) (TestService_TestStreamClientServerClient, error)
	TestStreamServer(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (TestService_TestStreamServerClient, error)
	TestBiDirectionalClientServer(ctx context.Context, opts ...grpc.CallOption) (TestService_TestBiDirectionalClientServerClient, error)
}

type testServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestServiceClient(cc grpc.ClientConnInterface) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) TestServer(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, "/TestService/TestServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) TestStreamClientServer(ctx context.Context, opts ...grpc.CallOption) (TestService_TestStreamClientServerClient, error) {
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[0], "/TestService/TestStreamClientServer", opts...)
	if err != nil {
		return nil, err
	}
	x := &testServiceTestStreamClientServerClient{stream}
	return x, nil
}

type TestService_TestStreamClientServerClient interface {
	Send(*TestRequest) error
	CloseAndRecv() (*TestResponse, error)
	grpc.ClientStream
}

type testServiceTestStreamClientServerClient struct {
	grpc.ClientStream
}

func (x *testServiceTestStreamClientServerClient) Send(m *TestRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *testServiceTestStreamClientServerClient) CloseAndRecv() (*TestResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(TestResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *testServiceClient) TestStreamServer(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (TestService_TestStreamServerClient, error) {
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[1], "/TestService/TestStreamServer", opts...)
	if err != nil {
		return nil, err
	}
	x := &testServiceTestStreamServerClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TestService_TestStreamServerClient interface {
	Recv() (*TestResponse, error)
	grpc.ClientStream
}

type testServiceTestStreamServerClient struct {
	grpc.ClientStream
}

func (x *testServiceTestStreamServerClient) Recv() (*TestResponse, error) {
	m := new(TestResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *testServiceClient) TestBiDirectionalClientServer(ctx context.Context, opts ...grpc.CallOption) (TestService_TestBiDirectionalClientServerClient, error) {
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[2], "/TestService/TestBiDirectionalClientServer", opts...)
	if err != nil {
		return nil, err
	}
	x := &testServiceTestBiDirectionalClientServerClient{stream}
	return x, nil
}

type TestService_TestBiDirectionalClientServerClient interface {
	Send(*TestRequest) error
	Recv() (*TestResponse, error)
	grpc.ClientStream
}

type testServiceTestBiDirectionalClientServerClient struct {
	grpc.ClientStream
}

func (x *testServiceTestBiDirectionalClientServerClient) Send(m *TestRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *testServiceTestBiDirectionalClientServerClient) Recv() (*TestResponse, error) {
	m := new(TestResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TestServiceServer is the server API for TestService service.
// All implementations must embed UnimplementedTestServiceServer
// for forward compatibility
type TestServiceServer interface {
	TestServer(context.Context, *TestRequest) (*TestResponse, error)
	TestStreamClientServer(TestService_TestStreamClientServerServer) error
	TestStreamServer(*TestRequest, TestService_TestStreamServerServer) error
	TestBiDirectionalClientServer(TestService_TestBiDirectionalClientServerServer) error
	mustEmbedUnimplementedTestServiceServer()
}

// UnimplementedTestServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTestServiceServer struct {
}

func (UnimplementedTestServiceServer) TestServer(context.Context, *TestRequest) (*TestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestServer not implemented")
}
func (UnimplementedTestServiceServer) TestStreamClientServer(TestService_TestStreamClientServerServer) error {
	return status.Errorf(codes.Unimplemented, "method TestStreamClientServer not implemented")
}
func (UnimplementedTestServiceServer) TestStreamServer(*TestRequest, TestService_TestStreamServerServer) error {
	return status.Errorf(codes.Unimplemented, "method TestStreamServer not implemented")
}
func (UnimplementedTestServiceServer) TestBiDirectionalClientServer(TestService_TestBiDirectionalClientServerServer) error {
	return status.Errorf(codes.Unimplemented, "method TestBiDirectionalClientServer not implemented")
}
func (UnimplementedTestServiceServer) mustEmbedUnimplementedTestServiceServer() {}

// UnsafeTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServiceServer will
// result in compilation errors.
type UnsafeTestServiceServer interface {
	mustEmbedUnimplementedTestServiceServer()
}

func RegisterTestServiceServer(s grpc.ServiceRegistrar, srv TestServiceServer) {
	s.RegisterService(&TestService_ServiceDesc, srv)
}

func _TestService_TestServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).TestServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TestService/TestServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).TestServer(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_TestStreamClientServer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServiceServer).TestStreamClientServer(&testServiceTestStreamClientServerServer{stream})
}

type TestService_TestStreamClientServerServer interface {
	SendAndClose(*TestResponse) error
	Recv() (*TestRequest, error)
	grpc.ServerStream
}

type testServiceTestStreamClientServerServer struct {
	grpc.ServerStream
}

func (x *testServiceTestStreamClientServerServer) SendAndClose(m *TestResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *testServiceTestStreamClientServerServer) Recv() (*TestRequest, error) {
	m := new(TestRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TestService_TestStreamServer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TestRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TestServiceServer).TestStreamServer(m, &testServiceTestStreamServerServer{stream})
}

type TestService_TestStreamServerServer interface {
	Send(*TestResponse) error
	grpc.ServerStream
}

type testServiceTestStreamServerServer struct {
	grpc.ServerStream
}

func (x *testServiceTestStreamServerServer) Send(m *TestResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _TestService_TestBiDirectionalClientServer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServiceServer).TestBiDirectionalClientServer(&testServiceTestBiDirectionalClientServerServer{stream})
}

type TestService_TestBiDirectionalClientServerServer interface {
	Send(*TestResponse) error
	Recv() (*TestRequest, error)
	grpc.ServerStream
}

type testServiceTestBiDirectionalClientServerServer struct {
	grpc.ServerStream
}

func (x *testServiceTestBiDirectionalClientServerServer) Send(m *TestResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *testServiceTestBiDirectionalClientServerServer) Recv() (*TestRequest, error) {
	m := new(TestRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TestService_ServiceDesc is the grpc.ServiceDesc for TestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestServer",
			Handler:    _TestService_TestServer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TestStreamClientServer",
			Handler:       _TestService_TestStreamClientServer_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "TestStreamServer",
			Handler:       _TestService_TestStreamServer_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TestBiDirectionalClientServer",
			Handler:       _TestService_TestBiDirectionalClientServer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "test-proto.proto",
}
